Mobs:
  CREEPER: 1.0
  SKELETON: 1.0
  SPIDER: 1.0
  GIANT: 1.0
  ZOMBIE: 1.0
  SLIME: 1.0
  GHAST: 1.0
  PIG_ZOMBIE: 1.0
  ENDERMAN: 1.0
  CAVE_SPIDER: 1.0
  SILVERFISH: 1.0
  BLAZE: 1.0
  MAGMA_CUBE: 1.0
  ENDER_DRAGON: 1.0
  WITHER: 1.0
  BAT: 1.0
  WITCH: 1.0
  ENDERMITE: 1.0
  GUARDIAN: 1.0
  PIG: 1.0
  SHEEP: 1.0
  COW: 1.0
  CHICKEN: 1.0
  SQUID: 1.0
  WOLF: 1.0
  MUSHROOM_COW: 1.0
  SNOWMAN: 1.0
  OCELOT: 1.0
  IRON_GOLEM: 1.0
  HORSE: 1.0
  RABBIT: 1.0
  VILLAGER: 1.0
Player: 1.0

MoneyReceived: '&7[&bKillReward&7] &e+ %amount%. You now have %balance%'